In [4]:
import numpy as np
RI_dict = {1: 0, 2: 0, 3: 0.58, 4: 0.90, 5: 1.12, 6: 1.24, 7: 1.32, 8: 1.41, 9: 1.45}
def AHP(A_arr):     #求特征向量
    A = np.array(A_arr)
#将矩阵列向量进行单位化0
    a_sum0 = A.sum(axis=0)
    B = A / a_sum0  
    

    b_sum = B.sum(axis=1)
    W = b_sum.sum()
    w_arr = []
    for w in b_sum:
        w_arr.append(w/W)
    print('特征向量为: %s' % w_arr)
    #一致性检验
    AW = []
    for a in A :
        aa = a * w_arr
        AW.append(aa.sum())
    result = np.array(AW) / np.array(w_arr)
    row = result.shape[0]
    Max = result.sum()/row
    print('最大特征值λMax: %s' % Max)
    CI = (Max - row) / (row - 1)
   
    CR = CI / RI_dict[row]
    print('CR: %s' % CR)
    if (CR<0.1): print('通过一致性检验！')
    else: print('未通过一致性检验！')

In [5]:
import pandas as pd
df = pd.read_excel("AHP_data.xlsx")
A=df.iloc[:,1:6].values
AHP(A)

特征向量为: [0.10051698109982732, 0.04119232069791139, 0.17001621264746442, 0.35780509024914975, 0.3304693953056471]
最大特征值λMax: 5.179341953712946
CR: 0.040031686096639714
通过一致性检验！

In [6]:
w=[0.10051698109982732, 0.04119232069791139, 0.17001621264746442, 0.35780509024914975, 0.3304693953056471]

In [7]:
dataset=pd.read_excel("customer_data_V4.xlsx")
Y=dataset.iloc[:,-1].values
dataset.head()

,ID,age,marital,income,house,business,property,debt,job,credit,relation,class
0,C001,1.0,1.0,0.333333,1.0,0.0,0.727273,1.0,1,0.0,0.50,1
1,C002,1.0,1.0,0.333333,1.0,0.5,1.000000,1.0,1,1.0,0.75,1
2,C003,1.0,1.0,1.000000,1.0,0.5,0.727273,0.5,1,0.8,0.75,1
3,C004,1.0,1.0,0.000000,1.0,0.0,0.363636,1.0,0,1.0,0.00,0
4,C005,1.0,1.0,0.333333,1.0,0.0,0.363636,0.5,1,0.8,0.00,0

In [8]:
from sklearn.preprocessing import MinMaxScaler
X1=dataset.iloc[:,[1,4]].values #个人情况
print("选择age与house")

选择age与house

In [9]:
w1=np.array([1,2]).T
x1=np.dot(X1,w1)
s1=MinMaxScaler()

In [10]:
X2=dataset.iloc[:,[2,10]].values #家庭情况
x2=np.dot(X2,np.array([1,3]).T)
print("选择marital与relation")

选择marital与relation

In [11]:
X3=dataset.iloc[:,[3,6,7]].values #财务情况
x3=np.dot(X3,np.array([1,2,-0.5]).T)
print("选择income，property和debt")

选择income，property和debt

In [12]:
X4=dataset.iloc[:,[5,8]] #职业情况
X4.head()

   business  job
0       0.0    1
1       0.5    1
2       0.5    1
3       0.0    0
4       0.0    1

In [13]:
x4=np.dot(X4,np.array([1,1]).T)

In [14]:
X5=dataset.iloc[:,[9]] #信用记录
X5.head()

   credit
0     0.0
1     1.0
2     0.8
3     1.0
4     0.8

In [15]:
x5=dataset.iloc[:,[9]].values
x5=np.dot(X5,np.array([1]).T)

In [16]:
m=[x1,x2,x3,x4,x5]
m=np.array(m)
pred=np.dot(m.T,np.array(w))

In [17]:
pred

array([0.98129711, 1.61429941, 1.61131761, 0.71185271, 1.10274004,
       1.39791514, 1.18811835, 0.78488673, 0.80037201, 1.47613083,
       1.52161668, 1.44523659, 0.99491865, 1.07175114, 1.11567287,
       1.53192663, 0.87281731, 1.14447377, 1.23913853, 1.1919651 ,
       1.00409939, 1.75853779, 1.41684734, 1.06023599, 1.70835912,
       1.36983846, 1.55111104, 1.44436032, 1.59970779, 1.22883452,
       1.08851881, 1.63621916, 0.99491865, 1.44262517, 1.41945876,
       1.24856034, 1.5447831 , 1.28543612, 1.25718777, 1.12632987,
       1.06023599, 1.37863071, 0.66444925, 1.29577537, 1.03070639,
       1.23305147, 1.04039825, 0.95971901, 1.57828876, 1.56886695,
       1.1637582 , 1.52375129, 1.53071491, 1.58472876, 1.0049816 ,
       1.10274004, 0.99491865, 1.22117712, 1.3795837 , 1.30523241,
       1.70835912, 1.450353  , 1.67741149, 1.4546584 , 1.57311895,
       0.76852478, 1.42888057, 1.29577537, 1.25216603, 1.54053091,
       1.10003396, 1.42113476, 0.95093834, 1.22507647, 1.29316395,
       1.38768825, 1.60145517, 1.06165367, 1.23560967, 1.48421178,
       1.71996893, 1.63751903, 1.29581061, 1.63490743, 1.15722411,
       1.38214173, 1.03285277, 1.36014632, 1.40440854, 1.37178508,
       1.43493851, 0.99491865, 1.03641132, 0.8721527 , 1.30523241,
       1.16381159, 0.90569359, 1.27971394, 1.09113023, 1.30804998,
       1.34512505, 1.08434317, 1.45204698, 1.33963768, 1.45977481,
       1.28164259, 1.54952912, 0.90466455, 1.21632525, 1.36983846,
       1.47138462, 1.10772731, 1.23913853, 1.28087226, 1.12851787,
       0.88133344, 1.23913853, 1.31031377, 0.91392166, 1.03365278,
       1.63234941, 1.26740351, 1.49066905, 1.20705055, 1.18246646,
       0.98299109, 1.18112561, 0.7677304 , 1.11357953, 1.09113023,
       1.41945876, 1.45977481, 0.97529849, 1.30665009, 1.3722085 ,
       1.32928103, 1.42888057, 1.52805669, 1.40582622, 0.78876202,
       1.57398336, 0.95140321, 1.7701476 , 1.41945876, 1.58553978,
       1.2949284 , 1.21632525, 1.56620213, 1.37086764, 1.51388867,
       1.1469201 , 1.71996893, 1.51644688, 1.54222471, 1.01663214,
       1.53192663, 1.34512505, 0.89681319, 1.33963768, 0.99491865,
       1.33182126, 1.65927351, 1.3859531 , 0.78667973, 1.28087226,
       1.23720989, 1.13061715, 1.63234941, 1.23359795, 1.70835912,
       1.19637576, 1.21632525, 1.41945876, 0.86195435, 1.24620828,
       1.60145517, 0.90700485, 1.41303597, 0.54356527, 1.43787896,
       1.06145306, 1.42196375, 1.33894422, 1.19972816, 1.36278669,
       1.24579663, 1.70052486, 1.29581061, 0.68305181, 1.67746488,
       1.67485346, 1.20563287, 1.3117665 , 1.38081871, 1.63496083,
       1.17536801, 0.87848024, 1.63496083, 1.10196972, 1.27710234,
       1.16606376, 1.34205515, 1.34773647, 1.34773647, 1.15345419,
       0.70882964, 1.32928103, 0.65763331, 1.05159072, 0.85395022,
       1.63496083, 1.10411645, 1.0408569 , 1.41684734, 1.42201697,
       1.16450505, 1.6091296 , 1.42888057, 1.63496083, 1.46100942,
       1.21632525, 1.14804336, 1.38503566, 1.17779708, 1.14656711,
       1.450353  , 1.06023599, 1.36278669, 1.36278669, 1.45605828,
       1.37178508, 0.85165034, 1.05633665, 1.23146334, 1.30746111,
       1.15648313, 0.76852478, 1.6091296 , 0.93712331, 1.59496158,
       1.27715574, 1.30746111, 1.48555264, 1.53961329, 1.05528945,
       1.63496083, 1.72764355, 1.13793968, 1.45677521, 1.39537491,
       1.67228321, 1.12088413, 1.39938621, 0.63002615, 1.18523063,
       1.07429806, 1.48686437, 1.15476592, 1.24264956, 1.0653524 ,
       1.37863071, 1.56620213, 1.73664194, 1.2391033 , 1.21662559,
       1.4816827 , 1.28164259, 1.06023599, 1.61436467, 1.12632987,
       1.48766945, 1.26747457, 1.21106186, 1.46457976, 1.06023599,
       1.39657428, 1.47605964, 1.02531265, 1.47863582, 1.32414664,
       1.04011005, 1.33612665, 1.70046584, 1.37058531, 1.00406416,
       1.21531386, 1.48826425, 1.67746488, 1.47782481, 0.86326636,
       1.56881355, 1.41085466, 1.37783633, 1.4687732 , 1.42888057,
       1.08513755, 1.01780876, 0.97147594, 1.28610073, 1.1702516 ,
       0.80528228, 1.47057245, 1.63496083, 1.66585507, 1.26230495,
       1.13804563, 1.42888057, 1.29382856, 1.27003278, 1.53791931,
       1.450353  , 1.55245753, 1.18158426, 0.99202472, 1.34271414,
       1.04011005, 1.36216384, 1.02415415, 1.1637582 , 0.73076693,
       1.38300613, 1.47487784, 1.35412344, 1.40911951, 0.61775794,
       1.4687732 , 0.87780458, 1.36332217, 1.42888057, 1.46100942,
       1.39537491, 1.47138462, 1.55111104, 1.25718777, 1.21632525,
       1.29457542, 1.07107548, 1.18080804, 1.14447377, 1.11545514,
       1.0349584 , 1.23913853, 1.09766432, 1.75853779, 1.30000957,
       1.59376851, 1.09841117, 1.10196972, 1.19109389, 1.26480994,
       1.05131442, 1.48555264, 1.37058531, 1.22431225, 1.50227886,
       1.24055622, 1.15722411, 1.44436032, 0.90974602, 0.9588368 ,
       1.35803455, 1.27285034, 1.19172403, 0.92164949, 1.0149734 ,
       1.57311895, 1.34992389, 1.16542812, 1.27971394, 1.42888057,
       1.47138462, 1.46196281, 1.63621916, 1.40772562, 1.21942993,
       1.50739527, 1.03499364, 1.36983846, 1.42888057, 1.58685169,
       1.33702626, 1.2332986 , 0.92045575, 0.88133344, 1.34050208,
       1.31684223, 1.67746488, 0.75579112, 1.7014423 , 1.34512505,
       1.37432531, 1.17604367, 1.25781791, 1.36332217, 1.42888057,
       1.48294122, 1.27826084, 1.16025868, 1.1775562 , 1.56620213,
       1.37788972, 1.25965829, 0.73332514, 0.8894144 , 0.70310656,
       0.93988126, 1.11054488, 1.33612665, 0.88275112, 1.27003278,
       1.45935139, 1.0408569 , 1.34266074, 1.05762457, 1.25858824,
       1.21632525, 0.98284397, 1.02278982, 1.65753837, 1.63621916,
       1.35302409, 1.48686437, 1.51388867, 0.8037063 , 1.47138462,
       1.45977481, 0.89440167, 1.10196972, 1.26226971, 1.53530789,
       1.39368093, 1.41042455, 1.14447377, 1.27260896, 1.56886695,
       1.56886695, 1.20563287, 1.47613083, 1.16450505, 1.54478292,
       1.34699548, 1.54478292, 1.1637582 , 0.85467341, 1.42888057,
       1.41690056, 1.40440854, 1.51388867, 1.21632525, 1.21730719,
       1.46196281, 0.85432043, 0.70829416, 1.32839882, 1.34773647,
       1.46326803, 1.4159299 , 1.25425937, 1.48299443, 1.45977481,
       1.51388867, 1.29237613, 1.51388867, 1.450353  , 1.44262517,
       1.67097148, 1.434932  , 0.70882964, 0.90051192, 1.69930751,
       1.74655778, 1.31182553, 0.93394118, 1.24490841, 1.41684734,
       0.98343797, 0.86007802, 1.07107548, 0.9761807 , 1.48805763,
       0.97401617, 1.45605828, 1.07608001, 1.24520794, 0.89298399,
       1.27811373, 1.48774064, 1.23591002, 1.52805669, 1.04529765,
       1.36278669, 1.42888057, 1.38004839, 1.47613083, 1.21632525,
       1.0923473 , 1.37986603, 1.5447297 , 1.24997802, 1.43493851,
       1.30477376, 1.40952495, 1.06023599, 1.42880938, 1.04739099,
       1.53192663, 1.24055622, 1.27826084, 1.30874343, 1.09113023,
       1.63496083, 1.05670713, 1.32864614, 1.36332217, 1.52767463,
       1.48805763, 1.11832574, 1.1414507 , 0.91222769, 1.41858249,
       1.53192663, 1.15722411, 1.29514048, 1.6091296 , 1.36278669,
       1.57828876, 0.75602057, 1.27656687, 1.52156329, 1.3692089 ,
       0.64575883, 1.28087226, 1.20333385, 1.47273111, 1.48695252,
       1.57823536, 1.47351941, 1.14003923, 1.19109389, 1.31894178])

In [18]:
result=np.arange(len(pred))
for i in range(len(pred)):
    if pred[i]>0.89: result[i]=1
    else : result[i]=0
result

array([1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [19]:
Y

array([1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0], dtype=int64)

In [20]:
from sklearn.metrics import confusion_matrix
M=confusion_matrix(Y,result)
M

array([[ 40, 212],
       [  0, 288]], dtype=int64)

In [21]:
p_neur = (M[0,0]+M[1,1])/(M[0,0]+M[1,1]+M[0,1]+M[1,0])
print("准确度：",p_neur)

准确度： 0.6074074074074074